os:
  - linux
  - osx

language: node_js
cache: yarn
node_js:
  - "10"
  - "8"

jobs:
  include:
    - stage: "Installation"
      script: yarn install
    - stage: "Bundle Size Test"
      script: yarn test